#! /bin/bash

# ./genalladdrs.h [System.map file]

echo "// This file was automatically generated by running ./genalladdrs.h \"$1\"" > symbol_addrs.h

for NAME in do_munmap shmem_zero_setup vma_link perf_event_mmap unmap_region __audit_mmap_fd __mm_populate userfaultfd_unmap_complete security_mmap_file locks_mandatory_locked vm_area_free get_gate_vma vm_area_alloc vma_set_page_prot uprobe_mmap vm_stat_account vma_merge security_vm_enough_memory_mm is_file_shm_hugepages may_expand_vm vm_unacct_memory hugetlbfs_file_operations sysctl_max_map_count vm_munmap ptrace_check_attach ptrace_resume ptrace_regset ptrace_getsiginfo do_wait wake_up_state; do
    ADDR=`sudo cat "$1" | grep " $NAME$" | cut -d ' ' -f1`
    echo "#define ${NAME^^}_ADDR 0x$ADDR" >> symbol_addrs.h 
done